name: Code check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with Pytest
      run: |
        make test
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      with:
        coverageCommand: make test-coverage
        debug: true
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}